- name: to run the variables
  hosts: web
  become: yes
  vars_files:
  - vars.yml
  tasks:
  - name: run the variables through vars_files
    ansible.builtin.debug
      msg: "Hi i am learning {{COURSE}}, and the duration is {{DURATION}}, with the trainer {{SIVA KUMAR REDDY}}"