- name: variables with prompt
  hosts: web
  become: yes
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
    private: false
  - name: DURATION
    prompt: please enter the course duration
    private: false
  - name: TRAINER
    prompt: please enter the course trainer
    private: false
  tasks:
  - name: print the variable information
    ansible.builtin.debug:
    msg: "Hi, I am learning {{COURSE}}, with the {{DURATION}}, and the trainer is {{TRAINER}}"
