- name: variables with arguments
  hosts: local
  become: yes
  tasks:
  - name: print the variables with arguments
    ansible.builtin.debug:
      msg: "Hi I am learning {{COURSE}}, with duration {{DURATION}}, and the trainer is {{TRAINER}}"
      