- name: conditions
  hosts: web
  become: yes
  vars_prompt:
  - name: my_number
    prompt: please enter the number
    private: false
  
  tasks:
  - name: print this is if less than 10
    ansible.builtin.debug:
      msg: "Given number is {{my_number}} is less than 10"
    when: my_number | int < 10

  - name: print this if greater than or equal to 10
    ansible.builtin.debug:
      msg: "Given number is {{my_number}} is greater than or equal to 10"
    when: my_number | int >= 10